### ISSUE TITLE
Include "mean" spectra for Datacubes

### ISSUE THREAD

**Issue by knrobinson** [AlanRace/SpectralAnalysis#10]
It would be helpful to have the ability to generated mean spectra from datacubes, this would help when browsing peak picked data, or to do analysis of region in peak picked data.

**Comment by AlanRace** [comment]
When data is 'DataInMemory' (datacube generation or loading it in directly to memory), the mean spectrum is now automatically generated and included in the 'Spectrum List'. This is available in the latest source code version  6592a84
