### ISSUE TITLE
PCA image display colour scaling is not working properly

### ISSUE THREAD

**Issue by knrobinson** [AlanRace/SpectralAnalysis#11]
The diverging colour scaling on the PCA image window seems to not be able to centre itself on zero in most instances. 

Also would be nice to add support for different diverging colour scales, like Twilight etc, as the standard green/purple is not very clear, particularly when used in presentations

**Comment by AlanRace** [comment]
Diverging colour scale fixed in edbdea21aba225eb9a4b3d65bd6414a2a24a7c56
