### ISSUE TITLE
Normalisation on multi image composites not working

### ISSUE THREAD

**Issue by Rory-Steven** [AlanRace/SpectralAnalysis#2]
Hi Alan,
Using TIC or L-2 norm (possibly others I've not tried) on a composite image comprised from multiple, smaller images (combined using your converter) gives rise to errors. L-2 norm doesn't seem to work at all. TIC norm appears to work but when I try to create a mean spectrum with TIC norm a blank spectrum is returned also images created are binary with pixel values of 0 or nan. I've checked it on one of the original single images which made up the composite and the issue still occurs for TIC norm mean spectra and image generation but L-2 norm seems to work. Original images were non-rectangular. 
Rory

**Comment by AlanRace** [comment]
Hi Rory,
This should be fixed in the latest commit (https://github.com/AlanRace/SpectralAnalysis/commit/41a83fe22c05d199c53d4d94622042e193a1c215). Please download the latest version of both MOOGL and SpectralAnalysis and let me know if you're still experiencing this issue.
