### ISSUE TITLE
Darkened images after ROI import

### ISSUE THREAD

**Issue by adamjtaylor** [AlanRace/SpectralAnalysis#3]
After loading an ROI, ion images appear darkened, even with ROI display unticked.

**Comment by AlanRace** [comment]
This should have been fixed in this commit (https://github.com/AlanRace/SpectralAnalysis/commit/2783966065651a61ff55910ed0cb89b364b553e5). Please redownload the latest versions of both MOOGL and SpectralAnalysis and let me know if you are still experiencing this issue.
