### ISSUE TITLE
Question on recent alterations of peak picking.

### ISSUE THREAD

**Issue by inesboxexa** [AlanRace/SpectralAnalysis#31]
Hi Alan,

I got the error below:

Error using SpectralPeakDetection/process
Too many input arguments.

Error in f_saving_peaks_details (line 24)
        [ ~, ~, peakDetails ] = peakPicking.process(totalSpectrum_mzvalues, totalSpectrum_intensities); % peak pick total spectrum

Could you help?

Thanks,
Teresa

**Comment by AlanRace** [comment]
Hi Teresa,
The new process function takes a `SpectralData` instance and returns an array of `Peak` instances.

You should be able to change your line to:

`peaks = peakPicking.process(SpectralData(totalSpectrum_mzvalues, totalSpectrum_intensities));`

The peaks array then has fields for the peak centroid, min and max spectral channels etc. You can get these as a vector for example:

`centroids = [peaks.centroid];`

Hope that helps!

Alan

________________________________

**Comment by AlanRace** [comment]
Hi Teresa,
The new process function takes a `SpectralData` instance and returns an array of `Peak` instances.

You should be able to change your line to:

`peaks = peakPicking.process(SpectralData(totalSpectrum_mzvalues, totalSpectrum_intensities));`

The peaks array then has fields for the peak centroid, min and max spectral channels etc. You can get these as a vector for example:

`centroids = [peaks.centroid];`

Hope that helps!

Alan

**Comment by inesboxexa** [comment]
Hi Alan,

Thank you very much, issue solved!

Teresa
