### ISSUE TITLE
[ISSUE] Creating a new data representation.

### ISSUE THREAD

**Issue by inesboxexa** [AlanRace/SpectralAnalysis#32]
Hi Alan,

I believe this is still related with the changes made to SA recently.

In my function to save a datacube (from a lists of peak details), I have now the following code:

reduction = DatacubeReduction(peakTolerance, toleranceUnit, output, intensityDataType, storageType);
        
        addlistener(reduction, 'FastMethods', @(src, canUseFastMethods)disp(['! Using fast Methods?   ' num2str(canUseFastMethods.bool)]));
        
        peakList.minSpectralChannel = [ datacubeonly_peakDetails(:,1) ];
        peakList.centroid = [ datacubeonly_peakDetails(:,2) ];
        peakList.maxSpectralChannel = [ datacubeonly_peakDetails(:,3) ];
        
        reduction.setPeakList(peakList);
        
        datacube = reduction.process(data);
        datacube = datacube.get(1);
        datacube = datacube.saveobj();

Which however doesnt seem to work. I got the following error:

Assignment has more non-singleton rhs dimensions than non-singleton subscripts

Error in DatacubeReduction/processOtherParser (line 247)
                                data{pixelListIndex}(row, :) = images(i, :);

Error in DatacubeReduction/process (line 51)
                    dataRepresentationList = this.processOtherParser(dataRepresentation);

Error in f_saving_data_cube (line 47)
        datacube = reduction.process(data);

Let me know what you think it could be.

Thanks,
Teresa

**Comment by AlanRace** [comment]
Hi Teresa,
Are you sure that you have the latest version downloaded? I believe this bug was fixed in commit b1624cf8056348bbdb97a4a92780a91a25f05c6b (roughly 4 days ago).

Can you confirm that this is still an issue with the latest version?

Thanks,

Alan

**Comment by inesboxexa** [comment]
Hi Alan,

I just got the most recent version, but using it didnt solve the issue. I'm still getting the erro:

Assignment has more non-singleton rhs dimensions than non-singleton subscripts

Error in DatacubeReduction/processOtherParser (line 246)
                            data{pixelListIndex}(row, :) = images(col, :);

Error in DatacubeReduction/process (line 51)
                    dataRepresentationList = this.processOtherParser(dataRepresentation);

Error in f_saving_data_cube (line 47)
        datacube = reduction.process(data);

Could it be that:

peakList.minSpectralChannel = [ datacubeonly_peakDetails(:,1) ];
peakList.centroid = [ datacubeonly_peakDetails(:,2) ];
peakList.maxSpectralChannel = [ datacubeonly_peakDetails(:,3) ];

reduction.setPeakList(peakList);

Is not appropriate? Maybe I'm missing to define something? (in addition to the PeakList)

Thanks,
Teresa

**Comment by AlanRace** [comment]
I think it could be. `peakList` should be an array of `Peak` instances. This should create a proper `peakList`

```matlab
peakList = [];

% This is where the peaks came from
originalSpectrum = SpectralData(mzs, counts);

for i = 1:size(datacubeonly_peakDetails, 1)
     % Peak takes the following arguments: spectralData, centroid, intensity, minSpectralChannel, maxSpectralChannel
     peak = Peak(originalSpectrum, datacubeonly_peakDetails(i, 2), datacubeonly_peakDetails(i, 4), datacubeonly_peakDetails(i,1), datacubeonly_peakDetails(i, 3));
                    
     % Make a vector of Peak instances. If the list is empty then we need to initiate it with the peak, otherwise add peak to end of list
     if isempty(peakList)
         peakList = peak;
     else
         peakList(i) = peak;
     end
end
```

**Comment by inesboxexa** [comment]
Hi Alan,

Thank you very much! It worked!

Teresa
