### ISSUE TITLE
Freezing on datacube export to imzML [BUG]

### ISSUE THREAD

**Issue by adamjtaylor** [AlanRace/SpectralAnalysis#33]
**Describe the bug**
It is desirable to export a ROI of a imzML directly to a new imzML for separate processing without any preprocessing or peak picking. Currently, when doing direct export to imzML, MATLAB freezes for a long time and there is no visual confirmation that anything is actually happening. The export is usually successful after some time but this is not clear to the user as it appears frozen.

**To Reproduce**
Steps to reproduce the behaviour:
1. import a imzML on disk.
2. Create a region of interest
3.  Click data reduction > datacube
4. Select "export at location" and "imzML"
5. Select output destination and start export

**Expected behaviour**
Spectral analysis to be usable during export or feedback to user that export is in progress and when complete
Desirable: Progress bar showing export

**Software version**
- NPL X:/SpectralAnalysis
- Source code

**If using source code, MATLAB version (please complete the following information):**
 - e.g. MATLAB R2019a

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 10

**Comment by adamjtaylor** [comment]
Further to this the output imzML's include blank pixels - sometimes to the size of the original dataset, but this does not seem consistent. 
The expected behaviour would for there to be no empty pixels - only the selected ROI to be included. 
![image](https://user-images.githubusercontent.com/14945787/89331671-1129bb80-d68a-11ea-9aac-3ca1621b3db6.png)

**Comment by adamjtaylor** [comment]
It looks like the excess area on export is solved in the current SA version. The freezing while exporting is still present.

**Comment by AlanRace** [comment]
Hi Adam,
Thanks for this. The progress bar should be working again for exporting to imzML in 20932a81a61f4e734ea1300a4b800ac2d14c06d9.

Previously the size of the output was dependent on the minimum size of all regions selected. This is now done per region, with an option included in the interface to keep original pixel locations.

Alan
