### ISSUE TITLE
User choice for ROI spacing on export [FEATURE]

### ISSUE THREAD

**Issue by adamjtaylor** [AlanRace/SpectralAnalysis#34]
**Is your feature request related to a problem? Please describe.**
Currently when a datacube from a single ROI is exported only pixels from this ROI are included in the new image
When multiple ROIs are used for datacube generation the ROI pixels are places in relation to the origin [1,1] pixel location of the original image.
This easily allows for the multiple ROIs to be viewed together later on but is sometimes not the desirable behaviour as this appears as "missing" pixels when viewing a single ROI exported in this way.

**Describe the solution you'd like**
The `Post Processing Method Editor: Datacube` window should include a user toggle option
- "User original pixel coordinates"
- "Use new pixel coordinates"
or similar
![image](https://user-images.githubusercontent.com/14945787/89461194-769dab00-d763-11ea-8a90-3991337f85bc.png)

**Describe alternatives you've considered**
Current workaround is to export ROI's one by one

**Comment by AlanRace** [comment]
This is now included in 20932a81a61f4e734ea1300a4b800ac2d14c06d9. It should work for both saving to imzML and for opening in a new window.

Alan
