### ISSUE TITLE
export of imageList to csv

### ISSUE THREAD

**Issue by Alex-Dexter** [AlanRace/SpectralAnalysis#4]
Export of image list to csv doesn't work. On looking the error is caused by the initial image being now defined as TIC not a m/z range. This can be fixed by changing the imageListToValues function in DataViewer to be from 1:length(imagesToGenerate) to 2:length(imagesToGenerate)

**Comment by AlanRace** [comment]
This is now fixed in [the latest commit](https://github.com/AlanRace/SpectralAnalysis/commit/7775269b14d8279a8e1618d7fe0c82ab620e9a2e).
