### ISSUE TITLE
Princomp removed as of 2018a

### ISSUE THREAD

**Issue by adamjtaylor** [AlanRace/SpectralAnalysis#5]
_Princomp_ has been removed from Matlab as of 2018a.  Suggest a new release using _pca_ instead to enable use of current Matlab versions.

**Comment by AlexHenderson** [comment]
I rolled my own, meaning you don't need the Statistics Toolbox either. 
https://bitbucket.org/AlexHenderson/chitoolbox/src/99b48cff98cc5c0307f0fa6ddae4c790480db79e/CHIToolbox/+utilities/chi_pca.m

**Comment by AlanRace** [comment]
Thanks Adam - I have updated this in the [latest commit] (https://github.com/AlanRace/SpectralAnalysis/commit/060e70e19485a8af760596931b596310dbfa1cc5)

Alex - It would be great to integrate your version which doesn't require the Statistics Toolbox, but unfortunately the licences aren't compatible (as far as I understand it...).

**Comment by adamjtaylor** [comment]
This has been fixed in commit (060e70e)
