### ISSUE TITLE
Loading in memory error

### ISSUE THREAD

**Issue by educhicano** [AlanRace/SpectralAnalysis#7]
Hi Alan,
latest version doesn't allow me to load in memory. It gives me the following error messages in console:
![spectralanalysis_console](https://user-images.githubusercontent.com/21240536/54917204-8d8b8680-4efb-11e9-95ba-33b6e76d43dd.PNG)

**Comment by AlanRace** [comment]
Duplicate of https://github.com/AlanRace/SpectralAnalysis/issues/9
