### ISSUE TITLE
Error for mean spectra of ROIs from datacube

### ISSUE THREAD

**Issue by adamjtaylor** [AlanRace/SpectralAnalysis#8]
Making the mean spectra of a region of interest fails with the following error:

`Java exception occurred
java.lang.Runtime.Exception: Incorrect size
at
com.alanmrace.JSpectralAnalysis.RegionOfInterest.addPixels(RegionOfInterest,java:32)`

This does not occur for mean spectra of the whole dataset
This is was for a DataInMemory datacube.
It does not occur for a DataOnDisk non-peak picked dataset
This was occurring for Melina in the v1.2 release running on MATLAB R2018b.

**Comment by AlanRace** [comment]
Hopefully this was fixed in commit https://github.com/AlanRace/SpectralAnalysis/commit/fc9f72954667d47f0cec1c8b5437ce4bec9a5221. This is included in v1.2.1 (https://github.com/AlanRace/SpectralAnalysis/releases/tag/v1.2.1). Can you try and replicate this issue in v1.2.1?
