### ISSUE TITLE
Data Reduction Datacube 

### ISSUE THREAD

**Issue by educhicano** [AlanRace/SpectralAnalysis#9]
Hi Alan,
I'm trying to perform a clustering over my imzML images and then save the cluster of interest in a new imzML file but when I try to do it by using Datacube reduction (Process Separately option), SpectralAnalysis/Matlab shows an error  when imzML is selected as Output: No constructor 'com.alanmrace.jimzmlparser.imzML.ImzML' with matching signature found.
How can I solve it?
Thanks in advance!

**Comment by educhicano** [comment]
Hi again Alan. Thanks for your time!
I've changed java heap memory from 384MB to the maximum allowed, 8121MB but the error continues. The imzML file and associated ibd file I'm trying to cluster and save are 6380KB and 266876KB respectively, so, its not a huge dataset like other I've here (more than 3gb).
I'm using Matlab2015b
![java_heap](https://user-images.githubusercontent.com/21240536/56727246-92d52e80-6750-11e9-9dc3-64dc37e03f26.PNG)

**Comment by AlanRace** [comment]
Hello, 
Can you tell me exactly what settings you used when trying to perform DatacubeReduction? It may be because of the large amount of empty space in the data that it is failing with the memory issues. Did you just try and create the datacube for a single region of interest?

Thanks,

Alan

**Comment by AlanRace** [comment]
Hello again,
This should now be fixed in the latest version of SpectralAnalysis. I believe the problem was with Bruker data and the absolute coordinate system (rather than relative) resulting in large images. 

Thanks,

Alan
